//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approximation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Approximation.Properties.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ab-Exponential regression.
        /// </summary>
        internal static string abExponential {
            get {
                return ResourceManager.GetString("abExponential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addicional informacion.
        /// </summary>
        internal static string AddInf {
            get {
                return ResourceManager.GetString("AddInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear graph.
        /// </summary>
        internal static string ClearGraph {
            get {
                return ResourceManager.GetString("ClearGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear input.
        /// </summary>
        internal static string ClearInput {
            get {
                return ResourceManager.GetString("ClearInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation coefficient.
        /// </summary>
        internal static string Correlation {
            get {
                return ResourceManager.GetString("Correlation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic regression.
        /// </summary>
        internal static string Cubic {
            get {
                return ResourceManager.GetString("Cubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficient of determination.
        /// </summary>
        internal static string Determination {
            get {
                return ResourceManager.GetString("Determination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits after the decimal point.
        /// </summary>
        internal static string DigitsText {
            get {
                return ResourceManager.GetString("DigitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average relative error, %.
        /// </summary>
        internal static string ErrorAp {
            get {
                return ResourceManager.GetString("ErrorAp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponential regression.
        /// </summary>
        internal static string Exponential {
            get {
                return ResourceManager.GetString("Exponential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic regression.
        /// </summary>
        internal static string Hyperbolic {
            get {
                return ResourceManager.GetString("Hyperbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data.
        /// </summary>
        internal static string InputData {
            get {
                return ResourceManager.GetString("InputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear regression.
        /// </summary>
        internal static string Linear {
            get {
                return ResourceManager.GetString("Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithmic regression.
        /// </summary>
        internal static string Logarithmic {
            get {
                return ResourceManager.GetString("Logarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no functions on graph.
        /// </summary>
        internal static string NoGraph {
            get {
                return ResourceManager.GetString("NoGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power regression.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadratic regression.
        /// </summary>
        internal static string Quadratic {
            get {
                return ResourceManager.GetString("Quadratic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart program to accept changes.
        /// </summary>
        internal static string RestartText {
            get {
                return ResourceManager.GetString("RestartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save an image.
        /// </summary>
        internal static string SaveImg {
            get {
                return ResourceManager.GetString("SaveImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a function.
        /// </summary>
        internal static string SelectFunction {
            get {
                return ResourceManager.GetString("SelectFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show addicional informacion.
        /// </summary>
        internal static string ShowInf {
            get {
                return ResourceManager.GetString("ShowInf", resourceCulture);
            }
        }
    }
}
